'use strict';

module.exports = {
  ADD_NOTE: 'ADD_NOTE',
  TOGGLE_EDIT_NOTE: 'TOGGLE_EDIT_NOTE',
  UPDATE_NOTE: 'UPDATE_NOTE',
  REMOVE_NOTE: 'REMOVE_NOTE',
  GET_ALL_NOTES: 'GET_ALL_NOTES',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  CREATE_USER: 'CREATE_USER',
  DISPLAY_CREATE_USER: 'DISPLAY_CREATE_USER',
  DISPLAY_LOGIN: 'DISPLAY_LOGIN',
  SELECT_CHAR: 'SELECT_CHAR',
  GET_USER_CHARS: 'GET_USER_CHARS'
};
