'use strict';

module.exports = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  CREATE_USER: 'CREATE_USER',
  DISPLAY_CREATE_USER: 'DISPLAY_CREATE_USER',
  DISPLAY_LOGIN: 'DISPLAY_LOGIN',
  SELECT_CHAR: 'SELECT_CHAR',
  GET_USER_CHARS: 'GET_USER_CHARS',
  ADD_NEW_CHAR: 'ADD_NEW_CHAR',
  UPDATE_CHAR: 'UPDATE_CHAR'
};
